<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>92244890-2155-4631-815c-b4ea0e885865</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.9" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBooks.Shared\MyBooks.Shared.csproj" />
  </ItemGroup>

</Project>
